version: '3.3'
services:
  mongodb:
    image: mongo:5.0.5
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
    secrets:
      - mongodb_password
    ports:
      - 27017:27017
    networks: 
      - internal
  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - internal
  main:
    build: 
      context: .
      dockerfile: infrastructure/main.Dockerfile
    environment:
      GETMETHODS: "false"
    secrets:
      - mongodb_password
    depends_on: 
      - mongodb
    restart: unless-stopped
    networks:
      - internal
    command: --host 0.0.0.0 --port 8081
  analytics:
    build: 
      context: .
      dockerfile: infrastructure/analytics.Dockerfile
    secrets:
      - mongodb_password
    depends_on: 
      - mongodb
    restart: unless-stopped
    networks:
      - internal
    command: --host 0.0.0.0 --port 8081
  nginx:
    build:
      context: .
      dockerfile: infrastructure/nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    links:
      - main
    volumes:
      - ./private/ssl-data/:/etc/letsencrypt
      - nginxdata:/etc/nginx
    networks:
      - internal
    restart: unless-stopped
secrets:
  mongodb_password:
    file: private/mongodb_password
volumes:
  mongodata:
    external: false
  nginxdata:
    external: false
networks:
  internal:
